name = "chatgpt-api"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "kv", id = "418d89b66ed940349b1fc1cc253a4d9f" }
]

[triggers]
crons = [ ]
